export const SEARCH_COUNTRY = "SEARCH_COUNTRY";
export const ASCENDING = "ASCENDING";
export const DESCENDING = "DESCENDING";
export const COUNTRYLIST = "COUNTRYLIST";
export const DELETELIST = "DELETELIST";
export const ADDLIST = "ADDLIST";

export const fields = {
  COUNTRYNAME: "COUNTRYNAME",
  COUNTRYCODE: "COUNTRYCODE",
  COUNTRYCALLINGCODE: "COUNTRYCALLINGCODE",
  COUNTRYCAPITAL: "COUNTRYCAPITAL",
  COUNTRYREGION: "COUNTRYREGION"
};
